# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primes',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primes',
            name='primes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
        ),
    ]
